# Generated by Django 3.2.15 on 2022-10-28 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instances', '0011_createinstance_migrateinstance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flavor',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='instance',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
