# Generated by Django 3.2.15 on 2022-10-28 13:53

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('instances', '0012_auto_20221028_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='Replay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('log_file', models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/replays', location=pathlib.PurePosixPath('/home/seki/Projects/forks/webvirtcloud/replays')), upload_to='', verbose_name='log file')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replays', to='instances.instance')),
            ],
        ),
    ]
