# Generated by Django 3.2.15 on 2022-12-02 15:03

import django.core.files.storage
from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('instances', '0013_replay'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='replay',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='replay',
            name='snapshot',
            field=models.CharField(blank=True, max_length=14, verbose_name='snapshot'),
        ),
        migrations.AlterField(
            model_name='replay',
            name='log_file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location=pathlib.PurePosixPath('/home/seki/Projects/py/webvirtcloud/replays')), upload_to='', verbose_name='log file'),
        ),
    ]
